version: '2'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=test
     - RABBITMQ_DEFAULT_PASS=password
  db:
    image: postgres:9.3.20
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
     - "5432:5432"
  eurekaserver:
    image: supplier/eureka-server
    ports:
      - "8761:8761"
  gateway:
    image: supplier/gateway-zuul
    depends_on:
      - eurekaserver
    ports:
      - "8080:8080"
  supplier:
    image: supplier/supplier-command
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8090:8090"
  

